services:
  - type: static
    name: cryptopilot
    env: static
    buildCommand: npm run build
    publishPath: dist
    headers:
      - for: '*.js'
        values:
          Content-Type: application/javascript
      - for: '*.mjs'
        values:
          Content-Type: application/javascript
      - for: '*.css'
        values:
          Content-Type: text/css
      - for: '*.png'
        values:
          Content-Type: image/png
      - for: '*.jpg'
        values:
          Content-Type: image/jpeg
      - for: '*.svg'
        values:
          Content-Type: image/svg+xml
    redirects:
      - source: /*
        destination: /free/index.html
        status: 200
